// components/sections/Events.vue
<template>
  <section id="aboutus" class="section">
    <h1 class="title">EVENTS</h1>
    <ul class="events">
      <li class="event">
        <img
          class="image"
          src="~/assets/events/kittenlt2.png"
          alt="KittenLT2"
        />
        <h1 class="name">KittenLT2</h1>
        <h2 class="subtitle">面白いことは、まだこの世にあふれている。</h2>
        <p class="state">2020年11月15日開催予定</p>
        <p class="description">
          KittenLTは、LTスタイルの勉強会です。<br />
          皆さんが気軽に話題を持ち寄って、発表できるような場を作りたい。<br />
          そういった信念で開催されることになりました 。<br />
          面白いことは、この世にあふれているはずです。
        </p>
        <a class="link" href="https://lt.teamkitten.tk/" target="_blank"
          >公式サイトへ</a
        >
      </li>
    </ul>
  </section>
</template>

<script>
export default {}
</script>

<style scoped>
.section {
  background: #fafafa;
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  padding: 32px;
  box-sizing: border-box;
}
.title {
  color: #707070;
  font-size: 2rem;
  font-weight: bold;
  text-align: center;
  margin-bottom: 48px;
}
.event {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
}
.image {
  width: 480px;
  max-width: 90%;
  box-shadow: 0 0 8px rgba(0, 0, 0, 0.16);
  margin-bottom: 32px;
  border-radius: 4px;
}
.name {
  font-size: 2rem;
  font-weight: bold;
  font-family: sans-serif;
  color: #555;
}
.subtitle {
  color: #555;
  font-weight: bold;
  margin-top: 12px;
}
.state {
  border: 2px solid #555;
  color: #555;
  padding: 12px 18px;
  font-weight: bold;
  margin-top: 12px;
}
.description {
  margin-top: 21px;
  line-height: 2;
  text-align: center;
  font-size: 0.9rem;
  color: #555;
}

.link {
  display: block;
  background: #008ffe;
  color: #fff;
  padding: 12px 18px;
  text-decoration: none;
  border-radius: 4px;
  margin-top: 12px;
  box-shadow: 0 0 4px rgba(0, 0, 0, 0.16);
}
</style>

// components/sections/Events.tsx
import React from 'react';
import styles from '../../styles/components/sections/Events.module.css';

const Events: React.FC = () => (
  <section className={styles.section}>
    <h1 className={styles.title}>EVENTS</h1>
    <ul className={styles.events}>
      <li className={styles.event}>
        <img
          className={styles.image}
          src="/events/kittenlt2.png"
          alt="KittenLT2"
          width="auto"
          height="auto"
        />
        <h1 className={styles.name}>KittenLT2</h1>
        <h2 className={styles.subtitle}>
          面白いことは、まだこの世にあふれている。
        </h2>
        <p className={styles.state}>ご来場ありがとうございました</p>
        <p className={styles.description}>
          KittenLTは、LTスタイルの勉強会です。
          <br />
          皆さんが気軽に話題を持ち寄って、発表できるような場を作りたい。
          <br />
          そういった信念で開催されることになりました 。<br />
          面白いことは、この世にあふれているはずです。
        </p>
        <a
          className={styles.link}
          href="https://lt.teamkitten.tk/"
          rel="noreferrer nooopener"
          target="_blank"
        >
          公式サイトへ
        </a>
      </li>
    </ul>
  </section>
);

export default Events;
